# Generated by Django 2.0.4 on 2018-04-19 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Front-end Developer', 'Front-end Developer'), ('Back-end Developer', 'Back-end Developer'), ('Project Manager', 'Project Manager')], max_length=10, null=True)),
                ('level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=10, null=True)),
                ('market_salary', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('github_user', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('date_started', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('race', models.CharField(choices=[('B', 'Black African'), ('C', 'Coloured'), ('I', 'Indian or Asian'), ('W', 'White'), ('N', 'None Dominant')], max_length=1, null=True)),
                ('positions', models.ManyToManyField(null=True, through='employees.PositionHistory', to='employees.Position')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('salary', models.FloatField()),
                ('review_type', models.CharField(choices=[('P', 'Performance Increase'), ('S', 'Starting Salary'), ('A', 'Annual Increase'), ('E', 'Expectation Review')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Profile'),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Position'),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='review',
            field=models.ManyToManyField(null=True, to='employees.Review'),
        ),
    ]
