# Generated by Django 2.0.4 on 2018-04-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('github_user', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('year_started', models.DateField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('race', models.CharField(choices=[('B', 'Black African'), ('C', 'Coloured'), ('I', 'Indian or Asian'), ('W', 'White'), ('N', 'None Dominant')], max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
