# Generated by Django 2.0.4 on 2018-04-19 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionhistory',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_history', to='employees.Position'),
        ),
        migrations.AlterField(
            model_name='positionhistory',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_history', to='employees.Review'),
        ),
    ]
