# Generated by Django 2.0.4 on 2018-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
