# Generated by Django 2.0.4 on 2018-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionhistory',
            old_name='employee',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='positionhistory',
            name='review',
            field=models.ManyToManyField(to='employees.Review'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(through='employees.PositionHistory', to='employees.Position'),
        ),
    ]
