# Generated by Django 2.0.4 on 2018-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180419_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'level')},
        ),
    ]
