# Generated by Django 2.0.4 on 2018-04-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180417_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='year_started',
            new_name='date_started',
        ),
    ]
