# Generated by Django 2.0.4 on 2018-04-18 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_auto_20180417_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeProfile',
            new_name='Profile',
        ),
    ]
