# Generated by Django 2.0.4 on 2018-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180419_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionhistory',
            name='review',
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='review',
            field=models.ManyToManyField(null=True, to='employees.Review'),
        ),
    ]
