# Generated by Django 2.0.4 on 2018-04-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180419_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='positionhistory',
            name='review',
            field=models.ManyToManyField(to='employees.Review'),
        ),
    ]
