# Generated by Django 2.0.4 on 2018-04-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180421_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionhistory',
            name='review',
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='employees.Review'),
        ),
    ]
