# Generated by Django 2.0.4 on 2018-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_position_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
