# Generated by Django 2.0.4 on 2018-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20180421_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
